http://localhost:5000/api/compounds

###
http://localhost:5000/api/compounds/af13f683-0c6d-431d-8390-ef515a868bf3

###
PATCH http://localhost:5000/api/compounds/af13f683-0c6d-431d-8390-ef515a868bf3 HTTP/1.1
content-type: application/json

    {
    "name": "12310MMeOH 12",
    "document": true,
    "aqueous_props": "Boric acid (pKa=9.3)",
    "adsorption_props": "Chelating resins",
    "analytical_techniques": "ICP",
    "spectroscopic_techniques": "XAX SAX",
    "uid": "af13f683-0c6d-431d-8390-ef515a868bf3"
    }

###
POST http://localhost:5000/api/compounds HTTP/1.1
content-type: application/json

    {
    "name": "Nafion 10MMeOH 12",
    "document": true,
    "aqueous_propsdelete_one": "Boric acid (pKa=9.3)",
    "adsorption_prdelete_oneops": "Chelating resins",
    "analytical_tedelete_onechniques": "ICP",
    "spectroscopicdelete_one_techniques": "XAX SAX",
    "uid": "1"
    }
###
DELETE http://localhost:5000/api/compounds/5c917b907524073330b468a45c916f7075240728ed4287d4 HTTP/1.1

object